### ISSUE TITLE
General stability

### ISSUE THREAD

**Issue by kenderipa** [mslalith/focus_launcher#322]
General stability of the launcher is pretty bad right now. It dies pretty often, sometimes several times in a row. Realme Tab Mini, Android 11.

**Comment by kenderipa** [comment]
After the last release the stability gets a lot better. I'm back to using Focus Launcher again. However, there are still specific thing that cause the launcher to crash, like trying to change the position of lunar phase information.

**Comment by mslalith** [comment]
That's great to hear. Can you explain more on the crash

> trying to change the position of lunar phase information.

What do you mean by this?

**Comment by kenderipa** [comment]
> What do you mean by this?

Sorry, not the widget position, but seemingly my location (Current Place). If I click on it, the launcher crashes.

**Comment by mslalith** [comment]
Seems fine to me. Try with [v0.8.1](https://github.com/mslalith/focus_launcher/releases/tag/v0.8.1). I've added crash reporting support.

**Comment by kenderipa** [comment]
> Seems fine to me. Try with [v0.8.1](https://github.com/mslalith/focus_launcher/releases/tag/v0.8.1). I've added crash reporting support.

Tries that. Launcher still crashes, if tapping Current Place.

Did you add Google Crashlytics?

**Comment by mslalith** [comment]
Ahh... I see the issue. It's due to device locale. I'll provide a fix.

> Did you add Google Crashlytics?

Something similar. I've added Sentry

**Comment by mslalith** [comment]
Fixed in [v0.8.2](https://github.com/mslalith/focus_launcher/releases/tag/v0.8.2)

**Comment by kenderipa** [comment]
Looks good. However, the launcher still crashes from time to time.

**Comment by IzzySoft** [comment]
@mslalith seeing you've added Sentry, and before I add the `Tracking` anti-feature: Is Sentry configured opt-in, or is it active by default?

**Comment by mslalith** [comment]
@IzzySoft currently it's active by default. I'll provide a user setting in next release

**Comment by IzzySoft** [comment]
Thanks! So shall I put up `Tracking` for now and you let me know once it's opt-in so I remove it again – or is that "next release" imminent (i.e. expected to ship within a few days)? I'd receive daily alerts with the AF missing and the "tracker" not "whitelisted".

**Comment by IzzySoft** [comment]
Tracking will show up now with the next sync. Please let me know when a version with opt-in is available.

**Comment by mslalith** [comment]
@IzzySoft There's a new Privacy setting in [v0.9.0](https://github.com/mslalith/focus_launcher/releases/tag/v0.9.0) to opt-out of crash reporting.

**Comment by IzzySoft** [comment]
Better, but that's the wrong way around: it should be opt-in. Remember, you should not do that without informed expressive consent. If you have it enabled by default, you have no consent at all – neither informed, nor expressive. So I have to keep the `Tracking` anti-feature in place for now:

> **Tracking:** the application tracks and reports your activity to somewhere – usually either without your consent, or by default (i.e. you’d have to actively disable it)

**Comment by mslalith** [comment]
hmm... I agree. It makes sense. I'll disable by default and provide opt-in setting. I'll be creating a separate issue for this (https://github.com/mslalith/focus_launcher/issues/413)

**Comment by mslalith** [comment]
@kenderipa Fixing crashes which are unexpected is an ongoing process. As your issue is resolved, I'll close this ticket.

**Comment by kenderipa** [comment]
Once again, the launcher has become almost unusable.

**Comment by kenderipa** [comment]
@mslalith, you should have a lot of crash reports from my tablet.
